hapijs/vision

lib/manager.js

I've run across this a few times during development where there's been an extra `.` or some such in the file path, which makes it fail, but makes it less than obvious to find in the code. Having the locations which were searched for the file is very helpful when debugging this.

Helpful path location checked

---

lib/manager.js
test/templates/valid/helpers/long.javascript
test/templates/valid/testHelpers.html

Slicing a path by the last 3 characters works for two character extensions, e.g. `'.js'` or `'.cs'` but not for longer extensions (`'.es6'` for example).
Using `Path.extname` will extract the proper extension name from a path, enabling support for files with long extensions.

Ensure _loaderHelpers registers actual filenames

---

lib/index.js
lib/manager.js
test/index.js
test/manager.js

Lab enabled the [no-shadow rule](http://eslint.org/docs/rules/no-shadow.html)
in hapijs/lab#371 (with exceptions provided by hapijs/lab#379).
This change corrects lint errors created by variable shadowing.

Fix lint errors.

---

README.md

Vision is loaded by default in Hapi 8.x and below. However, this
is going to change in version 9 (see hapijs/hapi#2626). This change provides an
example of how to register the vision plugin for Hapi >= 9.0.

Document plugin registration.

---

lib/manager.js
test/manager.js

Currently neither template compilation nor rendering occur until
after the 'onPreResponse' event. This means that extensions have
no way to intercept template related errors. This change moves the
compilation step to an earlier point in the request lifecycle so
that compilation errors are made available to the 'onPostHandler'
and 'onPreResponse' extension points. Rendering still happens
after 'onPreResponse' so that the context object can be modified
by extensions all the way up through the 'onPreResponse' event.
Fixes #10.

Make compilation errors available to extensions.

---

README.md
examples/nunjucks/index.js
lib/manager.js
test/manager.js

Some view engines (i.e. Nunjucks) rely on the manager configuration
and other state in order to render templates. This change provides
a convenience method to allow engines to initialize any additional
state and to update the engine configuration accordingly.

Engine initialization.

---

API.md

PR #15 added the ability to pass in an array of file paths to the 'path', 'partialsPath', 'helpersPath', and 'layoutsPath', but left the feature undocumented.

Update API documentation to match PR #15

---

lib/index.js
test/index.js

In some use cases it may make sense to load vision before any
connections have been configured. Similarly, multiple plugins in an
application may try to load vision. Since vision only deals with
template rendering, it is possible to do both of these if the
'connections' and 'once' attributes are provided in the plugin
attributes.
Resolves #63.

Update plugin attributes.

---

API.md

The API docs are a bit too dense on the `compile` method that the template libraries should export. These changes make them a bit more clear in my opinion.
One important change is the name of the argument from `callback` to `next`. This makes the docs more compliant with the hapi style guide because the given callback will likely be called on the same tick (if we are using `compileMode: async`, what is asynchronous is the execution of the compiled template, not the compilation of the template, which most likely is a synchronous task).
This also solves that ambiguity of having 2 parameters named `callback`.

make api docs a bit more clear on the 'compile' function

---

API.md
lib/index.js
lib/manager.js
test/index.js
test/manager.js
test/templates/valid/testHelpers.txt

Register rendering helpers programmatically

---

API.md
lib/manager.js
test/index.js
test/manager.js

Pass request to global context function when available

---

lib/manager.js
test/manager.js
test/templates/invalid/helpers/bad1.module
test/templates/invalid/helpers/bad2.module

Report errors when loading helpers

---

lib/manager.js
package.json

hoek@4.0.0 removed `Hoek.isAbsolutePath`, as `Path.isAbsolute` is available
on supported Node.js versions.

Use `Path.isAbsolute` instead of Hoek helper method

---

examples/handlebars/helpers.js
examples/handlebars/partials.js
lib/manager.js
test/manager.js
test/templates/valid/helpers/uppercaseToMutate.js
test/templates/valid/partials/navToMutate.html
test/templates/valid/partials/nested/navToMutate.html
test/templates/valid/testHelpersAndPartials.html

Why this change? If isCached is false, then users expect there to be changes when the file on disk changes. Build tools like `BrowserSync` also reload when files on disk change, so this adds a lot of 'it just works' value
Feedback welcome!

Load partials and helpers before compile if isCached is false

---

API.md
lib/index.js
lib/manager.js
package.json
test/index.js
test/manager.js
test/templates/plugin2/test.html
test/templates/plugin3/test.html

- Feedback welcome
- Set multiple: true, as it's required to pass plugin options
- Register vision via `server.register({ plugin: Vision, options: { ... });` where:
- options is a manager config, is synonymous with `server.views`
- Effectively, the only thing this adds is the ability to use
await server.register({
plugin: Vision,
options: {/* view manager options */}
});
// which will have the same effect as
await server.register(Vision);
server.views({/* view manager options */});

Pass manager options at registration time

---

lib/manager.js
package.json
test/manager.js
test/templates/valid/helpers/uppercaseESMDefault.js
test/templates/valid/helpers/uppercaseESMNamedExport.js
test/templates/valid/testHelpersESMDefault.html
test/templates/valid/testHelpersESMNamedExport.html

named export first, then default, then CJS
should resolve #145

Handle ESM for helpers

---

lib/index.js
lib/manager.js
lib/schemas.js

I figure I'll use this PR to open discussion or thinking around sharing Joi schemas and keeping them more centralized.
A couple times in projects I've enjoyed the thought of being able to use part of a Joi schema for both route payload validation and [schwifty](https://github.com/hapipal/schwifty) model schemas.
The `schemas / index.js` and friends, or `schemas.js` pattern is interesting to me, and I think makes a better use of Joi's existing extensibility via `.keys(` and other methods

Move Joi schemas to schemas file

---

lib/manager.js

The diff on this PR is not very helpful at all
What I did was turn the Manager into a class and all of the `internals.manager.prototype.this` and `internals.manager.prototype.that` functions are class functions now.
The tests haven't been touched

Convert manager to a class

---

README.md
examples/pug/index.js

Because I've spend a good full day breaking my head over this, I thought it might be a good idea to include how to use `options.basedir` for the Pug documentation. `options.basedir` allows you to use absolute paths when using `includes` or `extend`.
Not sure if this is something that should be included in the documentation, so feel free to reject it. But I think it would definitely help people.

Update Pug documentation

---

lib/manager.js
test/manager.js
test/testModule.js

#171 The change here is in the `bustRequireCache` method. In addition to deleting the module from the cache, all the references are also removed from the parent module.

Fix for memory leak cause by issue #171

---

API.md

Just a typo fix, no code changes. Noticed it as I was going over the README.

fix import typo in README

---

API.md

This fixes #337 on hapi.dev.  The markdown parser doesn't display headers with links in them.

Fix api headers

---

package.json

handlebars is only a devDependency, but update the version due to
a security advisory.
Refs: https://github.com/advisories/GHSA-q2c6-c6pm-g3gh

update handlebars dependency

---

API.md
lib/manager.js
test/manager.js

Rebased with hapijs/vision master. References #177

Bring back old async support PR

---

API.md
examples/eta/index.js
examples/eta/templates/index.eta

This PR adds the example for using [Etajs](https://eta.js.org/) as the template engine with vision.
Also fixes #208

Add example for Etajs

---

.github/workflows/ci-plugin.yml
LICENSE.md
lib/index.js
lib/manager.js
package.json
test/esm.js

- Test on node v14+ and hapi v20+.
- Update to node v18-compatible versions of hapi modules.
- Ensure all exports are available when used as ESM module.
If this looks good, this will go out as vision v7.

Support node v18 and hapi v21, drop node v12 and hapi v18/19

---

API.md
lib/index.d.ts
test/types-with-overrides.ts

Fixes #216.
Hi @damusix, it seems your types from #214 are more correct and I had totally forgottent that this PR was opened when I merged mine. I have ported your PR into this one and set you as coauthor of the commit, fixing the lab issue I mentioned in the #214. Thanks for your contribution!

fix: correct exported types
